using System.Text.Json.Serialization;

namespace Explore.Cli.Models.Explore;

public partial class Transaction
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("connection")]
    public Connection? Connection { get; set; }
}

public partial class Connection
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("schema")]
    public string? Schema { get; set; } //OpenAPI, AsyncAPI, Internal

    [JsonPropertyName("schemaVersion")]
    public string? SchemaVersion { get; set; } //3.0.3

    [JsonPropertyName("connectionDefinition")]
    public ConnectionDefinition? ConnectionDefinition { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paths")]
    public Dictionary<string, object>? Paths { get; set; }


    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("settings")]
    public Settings? Settings { get; set; }


    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("credentials")]
    public Credentials? Credentials { get; set; }
}

public partial class ConnectionV2
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonRequired]
    [JsonPropertyName("schema")]
    public string? Schema { get; set; } = "OpenAPI";//OpenAPI, AsyncAPI, Internal

    [JsonRequired]
    [JsonPropertyName("schemaVersion")]
    public string? SchemaVersion { get; set; } //3.0.3

    [JsonPropertyName("description")]
    public string? Description { get; set; } = "Generated by Explore.CLI";

    [JsonPropertyName("connectionDefinition")]
    public ConnectionDefinition? ConnectionDefinition { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paths")]
    public Dictionary<string, object>? Paths { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("settings")]
    public Settings? Settings { get; set; }


    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("credentials")]
    public Credentials? Credentials { get; set; }    
}

public partial class Components
{
    [JsonPropertyName("securitySchemes")]
    public SecuritySchemes? SecuritySchemes { get; set; }
}

public partial class SecuritySchemes
{
    [JsonPropertyName("BasicAuthCredentials")]
    public SecuritySchemeBasicAuthCredentials? BasicAuthCredentials { get; set; } 

    [JsonPropertyName("TokenCredentials")]
    public SecuritySchemeTokenCredentials? TokenCredentials { get; set; }      
}

public partial class SecuritySchemeTokenCredentials
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("scheme")]
    public string? Scheme { get; set; }    
}

public partial class SecuritySchemeBasicAuthCredentials
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("scheme")]
    public string? Scheme { get; set; }    
}

public partial class UsernamePasswordCredentials
{
    [JsonPropertyName("username")]
    public string? Username { get; set; }

    [JsonPropertyName("password")]
    public string? Password { get; set; }    
}

public partial class BasicAuthCredentials
{
    [JsonPropertyName("username")]
    public string? Username { get; set; }

    [JsonPropertyName("password")]
    public string? Password { get; set; }    
}

public partial class SaslPlainSslCredentials
{
    [JsonPropertyName("username")]
    public string? Username { get; set; }

    [JsonPropertyName("password")]
    public string? Password { get; set; }    
}

public partial class SaslPlainCredentials
{
    [JsonPropertyName("username")]
    public string? Username { get; set; }

    [JsonPropertyName("password")]
    public string? Password { get; set; }    
}

public partial class TokenCredentials
{
    [JsonPropertyName("token")]
    public string? Token { get; set; }
}

public partial class ApiKeyCredentials
{
    [JsonPropertyName("apiKey")]
    public string? ApiKey { get; set; }
}


public partial class Credentials
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("apiKey")]
    public string? ApiKey { get; set; }    

    [JsonPropertyName("token")]
    public string? Token { get; set; }    

    [JsonPropertyName("username")]
    public string? Username { get; set; }

    [JsonPropertyName("password")]
    public string? Password { get; set; }     
}

public partial class ConnectionDefinition
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("openapi")]
    public string? OpenApi { get; set; }
   
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("servers")]
    public List<Server>? Servers { get; set; }
    
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("paths")]
    public Dictionary<string, object>? Paths { get; set; }
}

public class PathsContent
{
    [JsonPropertyName("parameters")]
    public List<Parameter>? Parameters { get; set; }

    [JsonPropertyName("requestBody")]
    public RequestBody? RequestBody { get; set; }

}

public class RequestBody
{
    [JsonPropertyName("content")]
    public Dictionary<string, object>? Content { get; set; }
}


public class Parameter
{
    [JsonPropertyName("in")]
    public string? In { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }    

    [JsonPropertyName("schema")]
    public Schema? Schema { get; set; }

    [JsonPropertyName("examples")]
    public Examples? Examples { get; set; }


}

public class Schema
{
    [JsonPropertyName("type")]
    public string? type { get; set; }
}


public class Examples
{
    [JsonPropertyName("example")]
    public Example? Example { get; set; }        
}

public class Example
{
    [JsonPropertyName("value")]
    public string? Value { get; set; }        
}

public partial class Server
{
    //[RegularExpression(@"^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$")]
    [JsonPropertyName("url")]
    public string? Url { get; set; }
}

public class Settings
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("connectTimeout")]
    public long ConnectTimeout { get; set; }

    [JsonPropertyName("followRedirects")]
    public bool FollowRedirects { get; set; }

    [JsonPropertyName("encodeUrl")]
    public bool EncodeUrl { get; set; }
}


public class SpaceRequest
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; } = "Generated by Explore.CLI";
}

    public partial class SpaceResponse
    {
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("_links")]
        public Links? Links { get; set; }
    }

    public partial class Links
    {
        [JsonPropertyName("self")]
        public Apis? Self { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("apis")]
        public Apis? Apis { get; set; }

    }

    public partial class Apis
    {
        //[RegularExpression(@"^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$")]
        [JsonPropertyName("href")]
        public Uri? Href { get; set; }
    }

public class ApiRequestV2
{
    [JsonRequired]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonRequired]
    [JsonPropertyName("protocol")]
    public string? Protocol { get; set; } = "REST";


    [JsonPropertyName("currentVersion")]
    public ApiVersionTimeStamp? CurrentVersion { get; set; } = new ApiVersionTimeStamp();

    [JsonPropertyName("serverURLs")]
    public string[]? ServerURLs { get; set; } = Array.Empty<string>();

    [JsonRequired]
    [JsonPropertyName("type")]
    public string? Type { get; set; } = "custom";
}

public class ApiVersionTimeStamp
{
    [JsonRequired]
    [JsonPropertyName("version")]
    public string? Version { get; set; } = "1.0";

    [JsonRequired]
    [JsonPropertyName("timestamp")]
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
}

public class Endpoint
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public Guid? Id { get; set; }

    [JsonRequired]
    [JsonPropertyName("method")]
    public string? Method { get; set; }

    [JsonPropertyName("requestType")]
    public string? RequestType { get; set; } = "connection";

    [JsonRequired]
    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("connection")]
    public Connection? Connection { get; set; }
}


public class ApiRequest
{
    [JsonRequired]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonRequired]
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("servers")]
    public List<Server>? Servers { get; set; }
}

public partial class ApiResponseV2
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    [JsonRequired]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonRequired]
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("protocol")]
    public string? Protocol { get; set; }

    [JsonPropertyName("version")]
    public string? Version { get; set; }

    [JsonPropertyName("versionTimestamp")]
    public string? VersionTimestamp { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("serverUrls")]
    public ServerURLs? ServerUrls { get; set; } 
}

public class ServerURLs
{
    [JsonPropertyName("swaggerhub")]
    public string[]? SwaggerHub { get; set; }

    [JsonPropertyName("custom")]
    public string[]? Custom { get; set; } 
}

public partial class ApiResponse
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    [JsonRequired]
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonRequired]
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("servers")]
    public List<Server>? Servers { get; set; }
}

public partial class PagedSpaces
{
    [JsonPropertyName("_embedded")]
    public  EmbeddedSpaces? Embedded { get; set; }
}

public partial class EmbeddedSpaces 
{
    [JsonPropertyName("spaces")]
    public  List<SpaceResponse>? Spaces { get; set; }
}

public partial class PagedApis
{
    [JsonPropertyName("_embedded")]
    public  EmbeddedApis? Embedded { get; set; }
}

public partial class EmbeddedApis
{
    [JsonPropertyName("spaceApis")]
    public  List<ApiResponseV2>? Apis { get; set; }
}

public partial class PagedConnections
{
    [JsonPropertyName("_embedded")]
    public  EmbeddedConnections? Embedded { get; set; }
}

public partial class EmbeddedConnections
{
    [JsonPropertyName("connections")]
    public List<Connection>? Connections { get; set; }
}

public partial class PagedEndpoints
{
    [JsonPropertyName("_embedded")]
    public EmbeddedEndpoints? Embedded { get; set; }
}

public partial class EmbeddedEndpoints
{
    [JsonPropertyName("endpoints")]
    public List<Endpoint>? Endpoints { get; set; }
}
