// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using PactV4;
//
//    var contract = Contract.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace PactV4
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Schema for a Pact file
    /// </summary>
    public partial class Contract
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("consumer")]
        public Pacticipant Consumer { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("interactions")]
        public List<Interaction> Interactions { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public Metadata Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("provider")]
        public Pacticipant Provider { get; set; }
    }

    public partial class Pacticipant
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        public string Name { get; set; }
    }

    public partial class Interaction
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("comments")]
        public Comments Comments { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("interactionMarkup")]
        public InteractionMarkup InteractionMarkup { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("key")]
        public string Key { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pending")]
        public bool? Pending { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pluginConfiguration")]
        public Dictionary<string, object> PluginConfiguration { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("providerStates")]
        public ProviderStates? ProviderStates { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("request")]
        public Request Request { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("response")]
        public ResponseUnion? Response { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("type")]
        public InteractionType? Type { get; set; }

        [JsonPropertyName("contents")]
        public object Contents { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metaData")]
        public Dictionary<string, object> MetaData { get; set; }
    }

    public partial class Comments
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("testname")]
        public string Testname { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("text")]
        public List<string> Text { get; set; }
    }

    public partial class InteractionMarkup
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("markup")]
        public string Markup { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("markupType")]
        public MarkupType? MarkupType { get; set; }
    }

    public partial class ProviderState
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("params")]
        public Dictionary<string, object> Params { get; set; }
    }

    public partial class Request
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("body")]
        public Body Body { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("headers")]
        public Dictionary<string, string[]> Headers { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("method")]
        public Method? Method { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("path")]
        public string Path { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("query")]
        public Dictionary<string, string[]> Query { get; set; }

        [JsonPropertyName("contents")]
        public object Contents { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metaData")]
        public Dictionary<string, object> MetaData { get; set; }
    }

    public partial class Body
    {
        [JsonPropertyName("content")]
        public object Content { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("contentType")]
        public string ContentType { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("contentTypeHint")]
        public ContentTypeHint? ContentTypeHint { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("encoded")]
        public Encoded? Encoded { get; set; }
    }

    public partial class MessageContents
    {
        [JsonPropertyName("contents")]
        public object Contents { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("metaData")]
        public Dictionary<string, object> MetaData { get; set; }
    }


    public partial class ResponseClass
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("body")]
        public Body Body { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("headers")]
        public Dictionary<string, object> Headers { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("status")]
        public long? Status { get; set; }
    }

    public partial class Metadata
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("pactSpecification")]
        public PactSpecification PactSpecification { get; set; }
    }

    public partial class PactSpecification
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public enum MarkupType { CommonMark, Html };

    public enum ContentTypeHint { Binary, Text };

    public enum GeneratorType { Date, DateTime, MockServerUrl, ProviderState, RandomBoolean, RandomDecimal, RandomHexadecimal, RandomInt, RandomString, Regex, Time, Uuid };

    public enum Combine { And, Or };

    public enum MatchEnum { ArrayContains, Boolean, ContentType, Date, Datetime, Decimal, EachKey, EachValue, Equality, Include, Integer, NotEmpty, Null, Number, Regex, Semver, StatusCode, Time, Type, Values };

    public enum Method { Connect, Delete, Get, Head, MethodConnect, MethodDelete, MethodGet, MethodHead, MethodOptions, MethodPost, MethodPut, MethodTrace, Options, Post, Put, Trace };

    public enum InteractionType { AsynchronousMessages, SynchronousHttp, SynchronousMessages };

    public partial struct ProviderStates
    {
        public List<ProviderState> ProviderStateArray;
        public string String;

        public static implicit operator ProviderStates(List<ProviderState> ProviderStateArray) => new ProviderStates { ProviderStateArray = ProviderStateArray };
        public static implicit operator ProviderStates(string String) => new ProviderStates { String = String };
    }

    public partial struct Encoded
    {
        public bool? Bool;
        public string String;

        public static implicit operator Encoded(bool Bool) => new Encoded { Bool = Bool };
        public static implicit operator Encoded(string String) => new Encoded { String = String };
    }

    public partial struct ResponseUnion
    {
        public List<MessageContents> MessageContentsArray;
        public ResponseClass ResponseClass;

        public static implicit operator ResponseUnion(List<MessageContents> MessageContentsArray) => new ResponseUnion { MessageContentsArray = MessageContentsArray };
        public static implicit operator ResponseUnion(ResponseClass ResponseClass) => new ResponseUnion { ResponseClass = ResponseClass };
    }

    public partial class Contract
    {
        public static Contract FromJson(string json) => JsonSerializer.Deserialize<Contract>(json, PactV4.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Contract self) => JsonSerializer.Serialize(self, PactV4.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                MarkupTypeConverter.Singleton,
                ProviderStatesConverter.Singleton,
                ContentTypeHintConverter.Singleton,
                EncodedConverter.Singleton,
                GeneratorTypeConverter.Singleton,
                CombineConverter.Singleton,
                MatchEnumConverter.Singleton,
                MethodConverter.Singleton,
                ResponseUnionConverter.Singleton,
                InteractionTypeConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class MarkupTypeConverter : JsonConverter<MarkupType>
    {
        public override bool CanConvert(Type t) => t == typeof(MarkupType);

        public override MarkupType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "COMMON_MARK":
                    return MarkupType.CommonMark;
                case "HTML":
                    return MarkupType.Html;
            }
            throw new Exception("Cannot unmarshal type MarkupType");
        }

        public override void Write(Utf8JsonWriter writer, MarkupType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MarkupType.CommonMark:
                    JsonSerializer.Serialize(writer, "COMMON_MARK", options);
                    return;
                case MarkupType.Html:
                    JsonSerializer.Serialize(writer, "HTML", options);
                    return;
            }
            throw new Exception("Cannot marshal type MarkupType");
        }

        public static readonly MarkupTypeConverter Singleton = new MarkupTypeConverter();
    }

    internal class ProviderStatesConverter : JsonConverter<ProviderStates>
    {
        public override bool CanConvert(Type t) => t == typeof(ProviderStates);

        public override ProviderStates Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.String:
                    var stringValue = reader.GetString();
                    return new ProviderStates { String = stringValue };
                case JsonTokenType.StartArray:
                    var arrayValue = JsonSerializer.Deserialize<List<ProviderState>>(ref reader, options);
                    return new ProviderStates { ProviderStateArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type ProviderStates");
        }

        public override void Write(Utf8JsonWriter writer, ProviderStates value, JsonSerializerOptions options)
        {
            if (value.String != null)
            {
                JsonSerializer.Serialize(writer, value.String, options);
                return;
            }
            if (value.ProviderStateArray != null)
            {
                JsonSerializer.Serialize(writer, value.ProviderStateArray, options);
                return;
            }
            throw new Exception("Cannot marshal type ProviderStates");
        }

        public static readonly ProviderStatesConverter Singleton = new ProviderStatesConverter();
    }

    internal class ContentTypeHintConverter : JsonConverter<ContentTypeHint>
    {
        public override bool CanConvert(Type t) => t == typeof(ContentTypeHint);

        public override ContentTypeHint Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "BINARY":
                    return ContentTypeHint.Binary;
                case "TEXT":
                    return ContentTypeHint.Text;
            }
            throw new Exception("Cannot unmarshal type ContentTypeHint");
        }

        public override void Write(Utf8JsonWriter writer, ContentTypeHint value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ContentTypeHint.Binary:
                    JsonSerializer.Serialize(writer, "BINARY", options);
                    return;
                case ContentTypeHint.Text:
                    JsonSerializer.Serialize(writer, "TEXT", options);
                    return;
            }
            throw new Exception("Cannot marshal type ContentTypeHint");
        }

        public static readonly ContentTypeHintConverter Singleton = new ContentTypeHintConverter();
    }

    internal class EncodedConverter : JsonConverter<Encoded>
    {
        public override bool CanConvert(Type t) => t == typeof(Encoded);

        public override Encoded Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.True:
                case JsonTokenType.False:
                    var boolValue = reader.GetBoolean();
                    return new Encoded { Bool = boolValue };
                case JsonTokenType.String:
                    var stringValue = reader.GetString();
                    return new Encoded { String = stringValue };
            }
            throw new Exception("Cannot unmarshal type Encoded");
        }

        public override void Write(Utf8JsonWriter writer, Encoded value, JsonSerializerOptions options)
        {
            if (value.Bool != null)
            {
                JsonSerializer.Serialize(writer, value.Bool.Value, options);
                return;
            }
            if (value.String != null)
            {
                JsonSerializer.Serialize(writer, value.String, options);
                return;
            }
            throw new Exception("Cannot marshal type Encoded");
        }

        public static readonly EncodedConverter Singleton = new EncodedConverter();
    }

    internal class GeneratorTypeConverter : JsonConverter<GeneratorType>
    {
        public override bool CanConvert(Type t) => t == typeof(GeneratorType);

        public override GeneratorType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Date":
                    return GeneratorType.Date;
                case "DateTime":
                    return GeneratorType.DateTime;
                case "MockServerURL":
                    return GeneratorType.MockServerUrl;
                case "ProviderState":
                    return GeneratorType.ProviderState;
                case "RandomBoolean":
                    return GeneratorType.RandomBoolean;
                case "RandomDecimal":
                    return GeneratorType.RandomDecimal;
                case "RandomHexadecimal":
                    return GeneratorType.RandomHexadecimal;
                case "RandomInt":
                    return GeneratorType.RandomInt;
                case "RandomString":
                    return GeneratorType.RandomString;
                case "Regex":
                    return GeneratorType.Regex;
                case "Time":
                    return GeneratorType.Time;
                case "Uuid":
                    return GeneratorType.Uuid;
            }
            throw new Exception("Cannot unmarshal type GeneratorType");
        }

        public override void Write(Utf8JsonWriter writer, GeneratorType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case GeneratorType.Date:
                    JsonSerializer.Serialize(writer, "Date", options);
                    return;
                case GeneratorType.DateTime:
                    JsonSerializer.Serialize(writer, "DateTime", options);
                    return;
                case GeneratorType.MockServerUrl:
                    JsonSerializer.Serialize(writer, "MockServerURL", options);
                    return;
                case GeneratorType.ProviderState:
                    JsonSerializer.Serialize(writer, "ProviderState", options);
                    return;
                case GeneratorType.RandomBoolean:
                    JsonSerializer.Serialize(writer, "RandomBoolean", options);
                    return;
                case GeneratorType.RandomDecimal:
                    JsonSerializer.Serialize(writer, "RandomDecimal", options);
                    return;
                case GeneratorType.RandomHexadecimal:
                    JsonSerializer.Serialize(writer, "RandomHexadecimal", options);
                    return;
                case GeneratorType.RandomInt:
                    JsonSerializer.Serialize(writer, "RandomInt", options);
                    return;
                case GeneratorType.RandomString:
                    JsonSerializer.Serialize(writer, "RandomString", options);
                    return;
                case GeneratorType.Regex:
                    JsonSerializer.Serialize(writer, "Regex", options);
                    return;
                case GeneratorType.Time:
                    JsonSerializer.Serialize(writer, "Time", options);
                    return;
                case GeneratorType.Uuid:
                    JsonSerializer.Serialize(writer, "Uuid", options);
                    return;
            }
            throw new Exception("Cannot marshal type GeneratorType");
        }

        public static readonly GeneratorTypeConverter Singleton = new GeneratorTypeConverter();
    }

    internal class CombineConverter : JsonConverter<Combine>
    {
        public override bool CanConvert(Type t) => t == typeof(Combine);

        public override Combine Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "AND":
                    return Combine.And;
                case "OR":
                    return Combine.Or;
            }
            throw new Exception("Cannot unmarshal type Combine");
        }

        public override void Write(Utf8JsonWriter writer, Combine value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Combine.And:
                    JsonSerializer.Serialize(writer, "AND", options);
                    return;
                case Combine.Or:
                    JsonSerializer.Serialize(writer, "OR", options);
                    return;
            }
            throw new Exception("Cannot marshal type Combine");
        }

        public static readonly CombineConverter Singleton = new CombineConverter();
    }

    internal class MatchEnumConverter : JsonConverter<MatchEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(MatchEnum);

        public override MatchEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "arrayContains":
                    return MatchEnum.ArrayContains;
                case "boolean":
                    return MatchEnum.Boolean;
                case "contentType":
                    return MatchEnum.ContentType;
                case "date":
                    return MatchEnum.Date;
                case "datetime":
                    return MatchEnum.Datetime;
                case "decimal":
                    return MatchEnum.Decimal;
                case "eachKey":
                    return MatchEnum.EachKey;
                case "eachValue":
                    return MatchEnum.EachValue;
                case "equality":
                    return MatchEnum.Equality;
                case "include":
                    return MatchEnum.Include;
                case "integer":
                    return MatchEnum.Integer;
                case "notEmpty":
                    return MatchEnum.NotEmpty;
                case "null":
                    return MatchEnum.Null;
                case "number":
                    return MatchEnum.Number;
                case "regex":
                    return MatchEnum.Regex;
                case "semver":
                    return MatchEnum.Semver;
                case "statusCode":
                    return MatchEnum.StatusCode;
                case "time":
                    return MatchEnum.Time;
                case "type":
                    return MatchEnum.Type;
                case "values":
                    return MatchEnum.Values;
            }
            throw new Exception("Cannot unmarshal type MatchEnum");
        }

        public override void Write(Utf8JsonWriter writer, MatchEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MatchEnum.ArrayContains:
                    JsonSerializer.Serialize(writer, "arrayContains", options);
                    return;
                case MatchEnum.Boolean:
                    JsonSerializer.Serialize(writer, "boolean", options);
                    return;
                case MatchEnum.ContentType:
                    JsonSerializer.Serialize(writer, "contentType", options);
                    return;
                case MatchEnum.Date:
                    JsonSerializer.Serialize(writer, "date", options);
                    return;
                case MatchEnum.Datetime:
                    JsonSerializer.Serialize(writer, "datetime", options);
                    return;
                case MatchEnum.Decimal:
                    JsonSerializer.Serialize(writer, "decimal", options);
                    return;
                case MatchEnum.EachKey:
                    JsonSerializer.Serialize(writer, "eachKey", options);
                    return;
                case MatchEnum.EachValue:
                    JsonSerializer.Serialize(writer, "eachValue", options);
                    return;
                case MatchEnum.Equality:
                    JsonSerializer.Serialize(writer, "equality", options);
                    return;
                case MatchEnum.Include:
                    JsonSerializer.Serialize(writer, "include", options);
                    return;
                case MatchEnum.Integer:
                    JsonSerializer.Serialize(writer, "integer", options);
                    return;
                case MatchEnum.NotEmpty:
                    JsonSerializer.Serialize(writer, "notEmpty", options);
                    return;
                case MatchEnum.Null:
                    JsonSerializer.Serialize(writer, "null", options);
                    return;
                case MatchEnum.Number:
                    JsonSerializer.Serialize(writer, "number", options);
                    return;
                case MatchEnum.Regex:
                    JsonSerializer.Serialize(writer, "regex", options);
                    return;
                case MatchEnum.Semver:
                    JsonSerializer.Serialize(writer, "semver", options);
                    return;
                case MatchEnum.StatusCode:
                    JsonSerializer.Serialize(writer, "statusCode", options);
                    return;
                case MatchEnum.Time:
                    JsonSerializer.Serialize(writer, "time", options);
                    return;
                case MatchEnum.Type:
                    JsonSerializer.Serialize(writer, "type", options);
                    return;
                case MatchEnum.Values:
                    JsonSerializer.Serialize(writer, "values", options);
                    return;
            }
            throw new Exception("Cannot marshal type MatchEnum");
        }

        public static readonly MatchEnumConverter Singleton = new MatchEnumConverter();
    }

    internal class MethodConverter : JsonConverter<Method>
    {
        public override bool CanConvert(Type t) => t == typeof(Method);

        public override Method Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "CONNECT":
                    return Method.MethodConnect;
                case "DELETE":
                    return Method.MethodDelete;
                case "GET":
                    return Method.MethodGet;
                case "HEAD":
                    return Method.MethodHead;
                case "OPTIONS":
                    return Method.MethodOptions;
                case "POST":
                    return Method.MethodPost;
                case "PUT":
                    return Method.MethodPut;
                case "TRACE":
                    return Method.MethodTrace;
                case "connect":
                    return Method.Connect;
                case "delete":
                    return Method.Delete;
                case "get":
                    return Method.Get;
                case "head":
                    return Method.Head;
                case "options":
                    return Method.Options;
                case "post":
                    return Method.Post;
                case "put":
                    return Method.Put;
                case "trace":
                    return Method.Trace;
            }
            throw new Exception("Cannot unmarshal type Method");
        }

        public override void Write(Utf8JsonWriter writer, Method value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Method.MethodConnect:
                    JsonSerializer.Serialize(writer, "CONNECT", options);
                    return;
                case Method.MethodDelete:
                    JsonSerializer.Serialize(writer, "DELETE", options);
                    return;
                case Method.MethodGet:
                    JsonSerializer.Serialize(writer, "GET", options);
                    return;
                case Method.MethodHead:
                    JsonSerializer.Serialize(writer, "HEAD", options);
                    return;
                case Method.MethodOptions:
                    JsonSerializer.Serialize(writer, "OPTIONS", options);
                    return;
                case Method.MethodPost:
                    JsonSerializer.Serialize(writer, "POST", options);
                    return;
                case Method.MethodPut:
                    JsonSerializer.Serialize(writer, "PUT", options);
                    return;
                case Method.MethodTrace:
                    JsonSerializer.Serialize(writer, "TRACE", options);
                    return;
                case Method.Connect:
                    JsonSerializer.Serialize(writer, "connect", options);
                    return;
                case Method.Delete:
                    JsonSerializer.Serialize(writer, "delete", options);
                    return;
                case Method.Get:
                    JsonSerializer.Serialize(writer, "get", options);
                    return;
                case Method.Head:
                    JsonSerializer.Serialize(writer, "head", options);
                    return;
                case Method.Options:
                    JsonSerializer.Serialize(writer, "options", options);
                    return;
                case Method.Post:
                    JsonSerializer.Serialize(writer, "post", options);
                    return;
                case Method.Put:
                    JsonSerializer.Serialize(writer, "put", options);
                    return;
                case Method.Trace:
                    JsonSerializer.Serialize(writer, "trace", options);
                    return;
            }
            throw new Exception("Cannot marshal type Method");
        }

        public static readonly MethodConverter Singleton = new MethodConverter();
    }

    internal class ResponseUnionConverter : JsonConverter<ResponseUnion>
    {
        public override bool CanConvert(Type t) => t == typeof(ResponseUnion);

        public override ResponseUnion Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.StartObject:
                    var objectValue = JsonSerializer.Deserialize<ResponseClass>(ref reader, options);
                    return new ResponseUnion { ResponseClass = objectValue };
                case JsonTokenType.StartArray:
                    var arrayValue = JsonSerializer.Deserialize<List<MessageContents>>(ref reader, options);
                    return new ResponseUnion { MessageContentsArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type ResponseUnion");
        }

        public override void Write(Utf8JsonWriter writer, ResponseUnion value, JsonSerializerOptions options)
        {
            if (value.MessageContentsArray != null)
            {
                JsonSerializer.Serialize(writer, value.MessageContentsArray, options);
                return;
            }
            if (value.ResponseClass != null)
            {
                JsonSerializer.Serialize(writer, value.ResponseClass, options);
                return;
            }
            throw new Exception("Cannot marshal type ResponseUnion");
        }

        public static readonly ResponseUnionConverter Singleton = new ResponseUnionConverter();
    }

    internal class InteractionTypeConverter : JsonConverter<InteractionType>
    {
        public override bool CanConvert(Type t) => t == typeof(InteractionType);

        public override InteractionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Asynchronous/Messages":
                    return InteractionType.AsynchronousMessages;
                case "Synchronous/HTTP":
                    return InteractionType.SynchronousHttp;
                case "Synchronous/Messages":
                    return InteractionType.SynchronousMessages;
            }
            throw new Exception("Cannot unmarshal type InteractionType");
        }

        public override void Write(Utf8JsonWriter writer, InteractionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case InteractionType.AsynchronousMessages:
                    JsonSerializer.Serialize(writer, "Asynchronous/Messages", options);
                    return;
                case InteractionType.SynchronousHttp:
                    JsonSerializer.Serialize(writer, "Synchronous/HTTP", options);
                    return;
                case InteractionType.SynchronousMessages:
                    JsonSerializer.Serialize(writer, "Synchronous/Messages", options);
                    return;
            }
            throw new Exception("Cannot marshal type InteractionType");
        }

        public static readonly InteractionTypeConverter Singleton = new InteractionTypeConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
