// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using PactV3;
//
//    var contract = Contract.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace PactV3
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Schema for a Pact file
    /// </summary>
    public partial class Contract
    {
        
        [JsonPropertyName("consumer")]
        public Pacticipant Consumer { get; set; }

        
        [JsonPropertyName("interactions")]
        public List<Interaction> Interactions { get; set; }

        
        [JsonPropertyName("messages")]
        public List<Message> Messages { get; set; }

        
        [JsonPropertyName("metadata")]
        public Metadata Metadata { get; set; }

        
        [JsonPropertyName("provider")]
        public Pacticipant Provider { get; set; }
    }

    public partial class Pacticipant
    {
        
        [JsonPropertyName("name")]
        public string Name { get; set; }
    }

    public partial class Interaction
    {
        
        [JsonPropertyName("description")]
        public string Description { get; set; }

        
        [JsonPropertyName("providerStates")]
        public ProviderStates? ProviderStates { get; set; }

        
        [JsonPropertyName("request")]
        public Request Request { get; set; }

        
        [JsonPropertyName("response")]
        public Response Response { get; set; }
    }

    public partial class ProviderState
    {
        
        [JsonPropertyName("name")]
        public string Name { get; set; }

        
        [JsonPropertyName("params")]
        public Dictionary<string, object> Params { get; set; }
    }

    public partial class Request
    {
        [JsonPropertyName("body")]
        public object Body { get; set; }

        
        [JsonPropertyName("headers")]
        public Dictionary<string, object> Headers { get; set; }

        
        [JsonPropertyName("method")]
        public Method? Method { get; set; }

        
        [JsonPropertyName("path")]
        public string Path { get; set; }

        
        [JsonPropertyName("query")]
        public Dictionary<string, string[]> Query { get; set; }
    }

    public partial class Response
    {
        [JsonPropertyName("body")]
        public object Body { get; set; }

        
        [JsonPropertyName("headers")]
        public Dictionary<string, object> Headers { get; set; }

        
        [JsonPropertyName("status")]
        public long? Status { get; set; }
    }

    public partial class Message
    {
        [JsonPropertyName("contents")]
        public object Contents { get; set; }

        
        [JsonPropertyName("description")]
        public string Description { get; set; }

        
        [JsonPropertyName("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        
        [JsonPropertyName("metaData")]
        public Dictionary<string, object> MetaData { get; set; }

        
        [JsonPropertyName("providerState")]
        public string ProviderState { get; set; }
    }

    public partial class Metadata
    {
        
        [JsonPropertyName("pact-specification")]
        public PactSpecification PactSpecification { get; set; }

        
        [JsonPropertyName("pactSpecification")]
        public PactSpecificationClass MetadataPactSpecification { get; set; }

        
        [JsonPropertyName("pactSpecificationVersion")]
        public string PactSpecificationVersion { get; set; }
    }

    public partial class PactSpecificationClass
    {
        
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public partial class PactSpecification
    {
        
        [JsonPropertyName("version")]
        public string Version { get; set; }
    }

    public enum TypeEnum { Date, DateTime, RandomBoolean, RandomDecimal, RandomHexadecimal, RandomInt, RandomString, Regex, Time, Uuid };

    public enum Combine { And, Or };

    public enum MatchEnum { Boolean, ContentType, Date, Datetime, Decimal, Equality, Include, Integer, Null, Number, Regex, Time, Type, Values };

    public enum Method { Connect, Delete, Get, Head, MethodConnect, MethodDelete, MethodGet, MethodHead, MethodOptions, MethodPost, MethodPut, MethodTrace, Options, Post, Put, Trace };

    public partial struct ProviderStates
    {
        public List<ProviderState> ProviderStateArray;
        public string String;

        public static implicit operator ProviderStates(List<ProviderState> ProviderStateArray) => new ProviderStates { ProviderStateArray = ProviderStateArray };
        public static implicit operator ProviderStates(string String) => new ProviderStates { String = String };
    }

    public partial class Contract
    {
        public static Contract FromJson(string json) => JsonSerializer.Deserialize<Contract>(json, PactV3.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Contract self) => JsonSerializer.Serialize(self, PactV3.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                ProviderStatesConverter.Singleton,
                TypeEnumConverter.Singleton,
                CombineConverter.Singleton,
                MatchEnumConverter.Singleton,
                MethodConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class ProviderStatesConverter : JsonConverter<ProviderStates>
    {
        public override bool CanConvert(Type t) => t == typeof(ProviderStates);

        public override ProviderStates Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.String:
                    var stringValue = reader.GetString();
                    return new ProviderStates { String = stringValue };
                case JsonTokenType.StartArray:
                    var arrayValue = JsonSerializer.Deserialize<List<ProviderState>>(ref reader, options);
                    return new ProviderStates { ProviderStateArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type ProviderStates");
        }

        public override void Write(Utf8JsonWriter writer, ProviderStates value, JsonSerializerOptions options)
        {
            if (value.String != null)
            {
                JsonSerializer.Serialize(writer, value.String, options);
                return;
            }
            if (value.ProviderStateArray != null)
            {
                JsonSerializer.Serialize(writer, value.ProviderStateArray, options);
                return;
            }
            throw new Exception("Cannot marshal type ProviderStates");
        }

        public static readonly ProviderStatesConverter Singleton = new ProviderStatesConverter();
    }

    internal class TypeEnumConverter : JsonConverter<TypeEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum);

        public override TypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "Date":
                    return TypeEnum.Date;
                case "DateTime":
                    return TypeEnum.DateTime;
                case "RandomBoolean":
                    return TypeEnum.RandomBoolean;
                case "RandomDecimal":
                    return TypeEnum.RandomDecimal;
                case "RandomHexadecimal":
                    return TypeEnum.RandomHexadecimal;
                case "RandomInt":
                    return TypeEnum.RandomInt;
                case "RandomString":
                    return TypeEnum.RandomString;
                case "Regex":
                    return TypeEnum.Regex;
                case "Time":
                    return TypeEnum.Time;
                case "Uuid":
                    return TypeEnum.Uuid;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void Write(Utf8JsonWriter writer, TypeEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case TypeEnum.Date:
                    JsonSerializer.Serialize(writer, "Date", options);
                    return;
                case TypeEnum.DateTime:
                    JsonSerializer.Serialize(writer, "DateTime", options);
                    return;
                case TypeEnum.RandomBoolean:
                    JsonSerializer.Serialize(writer, "RandomBoolean", options);
                    return;
                case TypeEnum.RandomDecimal:
                    JsonSerializer.Serialize(writer, "RandomDecimal", options);
                    return;
                case TypeEnum.RandomHexadecimal:
                    JsonSerializer.Serialize(writer, "RandomHexadecimal", options);
                    return;
                case TypeEnum.RandomInt:
                    JsonSerializer.Serialize(writer, "RandomInt", options);
                    return;
                case TypeEnum.RandomString:
                    JsonSerializer.Serialize(writer, "RandomString", options);
                    return;
                case TypeEnum.Regex:
                    JsonSerializer.Serialize(writer, "Regex", options);
                    return;
                case TypeEnum.Time:
                    JsonSerializer.Serialize(writer, "Time", options);
                    return;
                case TypeEnum.Uuid:
                    JsonSerializer.Serialize(writer, "Uuid", options);
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class CombineConverter : JsonConverter<Combine>
    {
        public override bool CanConvert(Type t) => t == typeof(Combine);

        public override Combine Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "AND":
                    return Combine.And;
                case "OR":
                    return Combine.Or;
            }
            throw new Exception("Cannot unmarshal type Combine");
        }

        public override void Write(Utf8JsonWriter writer, Combine value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Combine.And:
                    JsonSerializer.Serialize(writer, "AND", options);
                    return;
                case Combine.Or:
                    JsonSerializer.Serialize(writer, "OR", options);
                    return;
            }
            throw new Exception("Cannot marshal type Combine");
        }

        public static readonly CombineConverter Singleton = new CombineConverter();
    }

    internal class MatchEnumConverter : JsonConverter<MatchEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(MatchEnum);

        public override MatchEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "boolean":
                    return MatchEnum.Boolean;
                case "contentType":
                    return MatchEnum.ContentType;
                case "date":
                    return MatchEnum.Date;
                case "datetime":
                    return MatchEnum.Datetime;
                case "decimal":
                    return MatchEnum.Decimal;
                case "equality":
                    return MatchEnum.Equality;
                case "include":
                    return MatchEnum.Include;
                case "integer":
                    return MatchEnum.Integer;
                case "null":
                    return MatchEnum.Null;
                case "number":
                    return MatchEnum.Number;
                case "regex":
                    return MatchEnum.Regex;
                case "time":
                    return MatchEnum.Time;
                case "type":
                    return MatchEnum.Type;
                case "values":
                    return MatchEnum.Values;
            }
            throw new Exception("Cannot unmarshal type MatchEnum");
        }

        public override void Write(Utf8JsonWriter writer, MatchEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case MatchEnum.Boolean:
                    JsonSerializer.Serialize(writer, "boolean", options);
                    return;
                case MatchEnum.ContentType:
                    JsonSerializer.Serialize(writer, "contentType", options);
                    return;
                case MatchEnum.Date:
                    JsonSerializer.Serialize(writer, "date", options);
                    return;
                case MatchEnum.Datetime:
                    JsonSerializer.Serialize(writer, "datetime", options);
                    return;
                case MatchEnum.Decimal:
                    JsonSerializer.Serialize(writer, "decimal", options);
                    return;
                case MatchEnum.Equality:
                    JsonSerializer.Serialize(writer, "equality", options);
                    return;
                case MatchEnum.Include:
                    JsonSerializer.Serialize(writer, "include", options);
                    return;
                case MatchEnum.Integer:
                    JsonSerializer.Serialize(writer, "integer", options);
                    return;
                case MatchEnum.Null:
                    JsonSerializer.Serialize(writer, "null", options);
                    return;
                case MatchEnum.Number:
                    JsonSerializer.Serialize(writer, "number", options);
                    return;
                case MatchEnum.Regex:
                    JsonSerializer.Serialize(writer, "regex", options);
                    return;
                case MatchEnum.Time:
                    JsonSerializer.Serialize(writer, "time", options);
                    return;
                case MatchEnum.Type:
                    JsonSerializer.Serialize(writer, "type", options);
                    return;
                case MatchEnum.Values:
                    JsonSerializer.Serialize(writer, "values", options);
                    return;
            }
            throw new Exception("Cannot marshal type MatchEnum");
        }

        public static readonly MatchEnumConverter Singleton = new MatchEnumConverter();
    }

    internal class MethodConverter : JsonConverter<Method>
    {
        public override bool CanConvert(Type t) => t == typeof(Method);

        public override Method Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "CONNECT":
                    return Method.MethodConnect;
                case "DELETE":
                    return Method.MethodDelete;
                case "GET":
                    return Method.MethodGet;
                case "HEAD":
                    return Method.MethodHead;
                case "OPTIONS":
                    return Method.MethodOptions;
                case "POST":
                    return Method.MethodPost;
                case "PUT":
                    return Method.MethodPut;
                case "TRACE":
                    return Method.MethodTrace;
                case "connect":
                    return Method.Connect;
                case "delete":
                    return Method.Delete;
                case "get":
                    return Method.Get;
                case "head":
                    return Method.Head;
                case "options":
                    return Method.Options;
                case "post":
                    return Method.Post;
                case "put":
                    return Method.Put;
                case "trace":
                    return Method.Trace;
            }
            throw new Exception("Cannot unmarshal type Method");
        }

        public override void Write(Utf8JsonWriter writer, Method value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Method.MethodConnect:
                    JsonSerializer.Serialize(writer, "CONNECT", options);
                    return;
                case Method.MethodDelete:
                    JsonSerializer.Serialize(writer, "DELETE", options);
                    return;
                case Method.MethodGet:
                    JsonSerializer.Serialize(writer, "GET", options);
                    return;
                case Method.MethodHead:
                    JsonSerializer.Serialize(writer, "HEAD", options);
                    return;
                case Method.MethodOptions:
                    JsonSerializer.Serialize(writer, "OPTIONS", options);
                    return;
                case Method.MethodPost:
                    JsonSerializer.Serialize(writer, "POST", options);
                    return;
                case Method.MethodPut:
                    JsonSerializer.Serialize(writer, "PUT", options);
                    return;
                case Method.MethodTrace:
                    JsonSerializer.Serialize(writer, "TRACE", options);
                    return;
                case Method.Connect:
                    JsonSerializer.Serialize(writer, "connect", options);
                    return;
                case Method.Delete:
                    JsonSerializer.Serialize(writer, "delete", options);
                    return;
                case Method.Get:
                    JsonSerializer.Serialize(writer, "get", options);
                    return;
                case Method.Head:
                    JsonSerializer.Serialize(writer, "head", options);
                    return;
                case Method.Options:
                    JsonSerializer.Serialize(writer, "options", options);
                    return;
                case Method.Post:
                    JsonSerializer.Serialize(writer, "post", options);
                    return;
                case Method.Put:
                    JsonSerializer.Serialize(writer, "put", options);
                    return;
                case Method.Trace:
                    JsonSerializer.Serialize(writer, "trace", options);
                    return;
            }
            throw new Exception("Cannot marshal type Method");
        }

        public static readonly MethodConverter Singleton = new MethodConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
